# Generated by Django 3.0.8 on 2020-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200711_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='current',
            new_name='value',
        ),
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.CharField(default='VOLTAGE', max_length=16),
        ),
    ]
